---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
```

Import and clean the cities data.
```{r}
cities <- read_csv('chandlerV2.csv', guess_max = 1597) %>% # increase guess max so columns are parsed correctly
  filter(City == 'London')
 mutate(ID = group_indices(., City, OtherName, Country), # give each city a unique idea, becuase some have the same name!
        Latitude = parse_number(Latitude), # some coordinates have unicade spaces "\xa0" in them
         Longitude = parse_number(Longitude)) %>%
  pivot_longer(starts_with(c('BC', 'AD')),
               names_to = c('era', 'year'), 
               names_sep = '_', 
               names_transform = list(year = as.integer),
               values_to = 'pop') %>%
  mutate(year_bp = if_else(era == 'AD', year - 2000, -1 * (year + 2000)),
         year = paste0(year, era)) %>%
  select(-OtherName, -era) %>%
  arrange(year_bp) %>%
  filter(!is.na(pop)) # remove rows with NA population
```

Check the result
```{r}
cities
```

```{r}
longevities <- cities %>% 
  group_by(ID, City, Latitude, Longitude) %>%
  summarise(start = min(year_bp),
            end = max(year_bp),
            longevity = end - start,
            .groups = 'drop') %>%
  arrange(-longevity)
```
Plot the results.
```{r}
ggplot(longevities, aes(Longitude, Latitude)) +
  geom_point(aes(color = longevity)) +
  scale_color_viridis_c()
```
```{r}
ggplot(longevities, aes(log(longevity + 100))) +
  geom_histogram() +
  scale_color_viridis_c()
```

```{r}
city_list <- c('Memphis', 'Girsu', 'Isin', 'Larsa', 'Mari', 'Nippur', 'Uruk', 'Susa', 'Umma', 'Ur', 'Thebes', 'Babylon', 'Loyang', 'Tanis', 'Pyongyang', 'Heliopolis', 'Assur', 'Nineveh', 'Rome', 'Alexandria', 'Luoyang', 'Seleucia', 'Antioch', 'Carthage', 'Anuradha-Pura', 'Ephesus', 'Capua', 'Taxilla', 'Beijing', 'Vijayanagar', 'Cairo', 'Hangzhou', 'Tabriz', 'Guar', 'Istanbul', 'Paris', 'Guangzhou', 'Nanjing', 'London', 'Tokyo', 'Osaka', 'Kyoto', 'New York', 'Mexico City', 'Moscow', 'Sao Pauolo', 'Los Angeles', 'Buenos Aires', 'Montevideo', 'Seoul', 'Mumbai', 'Shanghai')

test <- longevities %>%
  filter(City %in% city_list,
         longevity > 0, # should fill in these zeros because they're definitely wrong!
          ID != 912) # get rid of Memphis TN
```



```{r, fig.width = 8, fig.height = 4.5}
ggplot(test, aes(y = reorder(City, -start))) +
  geom_linerange(aes(xmin = start, xmax = end), alpha = 1) +
  geom_point(data = test, aes(x = start, y = City)) +
    geom_point(data = test, aes(x = end, y = City)) +
  geom_text(aes(x = start, label = City), nudge_x = -50, hjust = 1, size = 2.25) +
 # geom_vline(xintercept = -150, color = 'red', linetype = 2) +
  theme_minimal() +
  labs(x = 'Years before AD 2000', y = '') +
    scale_x_continuous(expand = c(.085, 0)) +
  theme(axis.text.y = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank())
ggsave('city_lifespans.png', width = 8, height = 4.5)
```

```{r}
mes_dat <- read_csv('urban_longevity_data.csv') #%>%
#  mutate(Site = if_else(str_detect(Site, 'Timbukt'), 'Timbuktu', Site))
  
ggplot(mes_dat, aes(y = reorder(Site, -Start))) +
  geom_linerange(aes(xmin = Start, xmax = End), alpha = 1) +
  geom_point(data = mes_dat, aes(x = Start, y = Site)) +
    geom_point(data = mes_dat, aes(x = End, y = Site)) +
  geom_text(aes(x = Start, label = Site), nudge_x = -50, hjust = 1, size = 2.25) +
 # geom_vline(xintercept = -150, color = 'red', linetype = 2) +
  theme_minimal() +
  labs(x = 'Years before AD 2000', y = '') +
    scale_x_continuous(expand = c(.085, 0)) +
  theme(axis.text.y = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank())
```

